name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}-${ GITHUB_REF }
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python - --version 1.8.1
          poetry install --no-root

      - name: Create .env.development.secrets
        run: |
          echo "PIXELLAB_SECRET=${{ secrets.API_SECRET }}" > .env.development.secrets

      - name: Test with pytest
        run: |
          $HOME/.local/bin/poetry run pytest -x

      - name: Build wheels
        run: |
          poetry version $(git tag --points-at HEAD)
          poetry build --format=wheel
